ln -s $PWD/vimrc ~/.vimrc
ln -s $PWD/bashrc ~/.bash_rc
ln -s $PWD/profile ~/.bash_profile
ln -s $PWD/shell-scripts ~/scripts
ln -s $PWD/rdbugrc ~/.rdbugrc
ln -s $PWD/irbrc ~/.irbrc
ln -s $PWD/gitconfig ~/.gitconfig
ln -s $PWD/git-completion.sh ~/.git-completion.sh
ln -s $PWD/gemrc ~/.gemrc
