ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/bashrc ~/.bash_rc
ln -sf $PWD/profile ~/.bash_profile
ln -sf $PWD/shell-scripts ~/scripts
ln -sf $PWD/rdbugrc ~/.rdbugrc
ln -sf $PWD/irbrc ~/.irbrc
ln -sf $PWD/gitconfig ~/.gitconfig
ln -sf $PWD/git-completion.sh ~/.git-completion.sh
ln -sf $PWD/gemrc ~/.gemrc
