#!/usr/bin/ruby
module GemInstaller
  def self.install_gem(gem_list_line)
    name, gem_versions = get_name_and_versions(gem_list_line)
    
    gem_versions.each do |gem_version|
      system "gem install #{name} --version '#{gem_version}'"
    end
  end
  
  def self.get_name_and_versions(gem_list_line)
    name, version = gem_list_line.split(' ')

    gem_versions = version.gsub(/\(|\)| /, '').split(',')
    
    return name, gem_versions
  end
end
File.open(File.expand_path('~/.gem_list'), 'r') do |f|
  f.each_line do |l|
    GemInstaller::install_gem(l)
  end
end