#!/usr/bin/env ruby
action = ARGV[0]

server = '/opt/local/lib/postgresql84/bin/pg_ctl -D /opt/local/var/postgres'

if action == 'start'
  cmd = "#{server} -l /opt/local/var/postgres/server.log start"
else
  cmd = "#{server} stop -s -m fast"
end

puts cmd
puts `#{cmd}`